#2rbzdym - Using mixins
alexeyshirko/cops pull request #86
Opened 2022-08-31 21:50 UTC by IzzXr

## Task

Issue: #2rbzdym

## Decision

> Please describe task description in more detail.
> If it was a bug, then describe what was causing the problem.

refactoring  styles

## Screenshots

> If you changed the UI, then you need to attach a screenshot/video.

2022-08-31 21:50 UTC, alexeyshirko commented
Task linked: [CU-2rbzdym Using mixins](https://app.clickup.com/t/2rbzdym)

2022-09-01 18:17 UTC, alexeyshirko requested changes

2022-09-01 18:17 UTC, alexeyshirko commented on src/core/components/ui/Icon/style/Icon.module.scss
> +@import "./../../../../../assets/style/mixins";
use `use` instead of `import` with an absolute path, it is shorter and always the same

2022-09-02 17:26 UTC, alexeyshirko commented on src/core/components/ui/Button/style/Button.module.scss
> +@use "src/assets/style/mixins" as mixin  ;
`as mixin  ;` what is it?

2022-09-02 20:48 UTC, IzzXr commented on src/core/components/ui/Button/style/Button.module.scss
> +@use "src/assets/style/mixins" as mixin  ;
use name mixins call an error, so I assigned a different name for the mixin, or is it called namespace control in another way

2022-09-07 19:49 UTC, alexeyshirko requested changes

2022-09-07 19:49 UTC, alexeyshirko commented on src/views/dispatcher/modules/Topbar/style/Topbar.module.scss
> +@import "./../../../../../assets/style/mixins";
`use`, not `import`

2022-09-07 19:49 UTC, alexeyshirko commented on src/core/components/ui/Button/style/Button.module.scss
> +@use "src/assets/style/mixins" as mixin  ;
remove space

2022-09-08 20:23 UTC, alexeyshirko approved these changes

2022-09-08 20:23 UTC, merged